### ISSUE TITLE
Feed RSS com problemas 🤡

### ISSUE THREAD

**Issue by X-ronin** [cypherpunksbr/cypherpunks.com.br#107]
![Screenshot_20221102-210547_Read You](https://user-images.githubusercontent.com/109928669/199625586-8ef3e627-7c68-4d97-8e25-1ab66e1dd30d.jpg)

**Comment by hotequil** [comment]
Estamos pesquisando sobre a solução do problema, obrigado por relatar.

**Comment by matheusbach** [comment]
Alteramos o RSS, corrigindo os links e colocando a descrição corretamente. Por favor, avise se é assim que gostaria de ver o conteúdo. Se não for, diga como que vamos mudar

**Comment by hotequil** [comment]
Olá, @X-ronin, fizemos essa alteração que você pediu, espero que goste! Se puder testar novamente, você já consegue ler os artigos.

**Comment by matheusbach** [comment]
Corrigido. Fechando issue por falta de feedback
