### ISSUE TITLE
dúvidas iniciais, gerais ou sem um tópico específico

### ISSUE THREAD

**Issue by ghost** [cypherpunksbr/cypherpunks.com.br#110]
Oi.

Gostaria de saber quem pode participar do grupo cypherpunks. Sobre isso, surgem dúvidas como:
- Existe alguma restrição para a participação, como um convite ou algo assim? 
- Como posso ser o colaborador do cypherpunks? 
- Existe alguma diretriz de conteúdo ou moderação para ser um colaborador desse repositório ou grupo?
- Devo pagar por algo ao ser colaborador do cypherpunks?
- É tudo gratuito, público? qual licença vocês utilizam para o texto ou código-fonte? 

Att,
villenmarx.

**Comment by hotequil** [comment]
Olá, @villenmarx! Muito obrigado pelo interesse no projeto, vou responder suas dúvidas sequencialmente abaixo:

- Não temos nenhuma restrição sobre quem pode participar, é livre para quem quiser contribuir;
- Existem diferentes formas, como: escrever e traduzir artigos, fazer artes, se comunicar divulgando conteúdo em nosso grupo no Telegram, melhorando nosso site e criando projetos com os outros indivíduos que participam do grupo;
- Sim, somos uma organização com regras privadas, temos o nosso [código de conduta](https://github.com/cypherpunksbr/comunidade/blob/main/CODE_OF_CONDUCT.md);
- Não, é totalmente voluntário, ninguém te cobra por nada;
- Sim, deixamos tudo a disposição da comunidade para cópia e alteração, utilizamos a licença [CC0](https://creativecommons.org/share-your-work/public-domain/cc0).

Espero ter ajudado e que você tenha interesse em ajudar! Muito obrigado.
