### ISSUE TITLE
direito, dever e responsabilidade autoral

### ISSUE THREAD

**Issue by ghost** [cypherpunksbr/cypherpunks.com.br#117]

**Comment by matheusbach** [comment]
Pode pegar o que quiser. Se nossa parte, não haverá problema. Acredito que os autores originais também não são arrombados o bastante pra achar ruim a divulgação das próprias ideias.

Pelo padrão moral da maioria dos autores que traduzimos os textos, é extremamente improvável qualquer tipo de requisição de direitos autorais, ainda mais com o conteúdo original já distribuído de forma gratuita.

Nós também temos a educação de sempre citar os autores e traduzir mantendo a ideia original dita, se distorcer ou enviesar os textos.

A melhor forma de crawlear os nossos textos é baixando o repositório cypherpunksbr/documentos aqui do GitHub. Lá estarão todos os textos presentes no site, bem como as imagens anexadas em alguns deles.

Há um disclaimer em nosso site e guia de contribuição, dizendo que todos os textos estarão sob Creative Commons ou alguma coisa assim que é extremamente frouxa para a distribuição do conteúdo e ideias presentes.
