### ISSUE TITLE
.MD ao invés de .HTML

### ISSUE THREAD

**Issue by davimello28** [cypherpunksbr/cypherpunks.com.br#16]
Senhores, 

Primeiramente, um agradecimento. Que projeto sensacional! 

Em segundo, uma sugestão. O que os senhores acham de inserirmos os arquivos em .MD ao invés de .HTML para os textos? Este processo facilitaria a tradução dos textos, e a integração com a página ainda seria possível através de algum compilador ou de um pequeno script no site.

**Comment by davimello28** [comment]
Como prova de conceito, realizei uma pequena conversão automática do HTML fornecido para .MD. e realizar a tradução. Estou postando por aqui o resultado antes de criar minha pull request para saber se a ideia será aprovada.

RPOW – Reusable Proofs of Work
Hal Finney
===============================

#### 15 de agosto de 2004\

[Archived website]({{url_for('rpow_site',%20path='index.html')}})

[GitHub](https://github.com/NakamotoInstitute/RPOW)

    To: cypherpunks@al-qaeda.net
    Subject: RPOW - Reusable Proofs of Work
    Date: Sun, 15 Aug 2004 10:43:09 -0700 (PDT)
    From: hal at finney dot org ("Hal Finney")

Gostaria de convidar os membros desta lista para experimentar o meu novo servidor baseado em hash, [rpow.net]({{url_for('rpow_site',%20path='index.html')}}).

Este sistema recebe o hashcash como uma Prova de Trabalho (Proof-of-Work, PoW), e em troca cria tokens assinados com RSA que eu chamo de Tokens de Prova de Trabalho Reutilizável. (RPOW Tokens). Os RPOWs podem ser transferidos de pessoa para pessoa e podem ser trocados por novos RPOWs a cada passo. Cada RPOW ou POW só pode ser usado uma única vez, mas como ele dá origem a um nove token, ele cria a sensação de estar utilizando o mesmo token.

Uma vez que RPOWs são criados a partir de POWs ou RPOWs de igual valor, eles são tão raros e "valiosos" quanto o hashcash utilizado para criá-los. Entretanto, eles são reutilizáveis, ao contrário do hashcash. 

O novo conceito do servidor é o modelo de segurança. O servidor RPOW é executado em um processador de alta segurança, o IBM 4758 Secure Cryptographic Coprocessor, em conformidade com o FIPS-140 nível 4. Esta placa é capaz de fornecer um atestado assinado da configuração usada, possibilitando que qualquer usuário (suficientemente motivado) possa verificar o código de acordo com o código publicado do sistema. Isso possibilita que qualquer um veja que não existem back-doors no sistema e que os RPOWs sejam criados somente quando forem fornecidos tokens POW/RPOW de igual valor.

É isso que cria confiança nos RPOWs, através da incorporação dos seus valores e a consciência de que eles foram, de fato, criados através de um token POW (hashcash) de igual valor.

Existem várias informações sobre o sistema em [rpow.net]({{url_for('rpow_site',%20path='index.html')}}), além do código fonte disponível para download.  Existe também uma interface CRUDE que permite você trocar POWs por RPOWs sem a necessidade de baixar o cliente.

Este sistema esta em beta no momento, então agradeço qualquer feedback caso alguém tenha a oportunidade de testar. Por favor, mantenha em mente que se houver qualquer problema que necessite eu recarregar o servidor, os tokens RPOWs criados anteriormente serão invalidados. Então não pegue pesado ao subir seus RPOWs ainda. 

Muito obrigado,

Hal Finney

**Comment by AvelinoMorganti** [comment]
Olá Davi! Primeiramente, fico muito feliz que você tenha gostado do nosso projeto. Adoraria que você fizesse parte entrando lá no grupo e contribuindo por aqui também.

Segundo. Refleti muito sobre a sua sugestão e levei aos membros mais ativos da comunidade. Tenho algumas conclusões que gostaria de compartilhar contigo até entrarmos em consenso. 

No momento, estamos desenvolvendo um script que envia o HTML daqui do nosso GitHub e manda para o nosso [site](https://cypherpunks.com.br/), que é feito em Wordpress. Fazemos isto por meio de um insert no banco de dados. Isso foi feito para melhorar o nosso controle de versão e fazermos todas as modificações  por aqui. O site apenas exibirá os conteúdos que já estão aqui no GitHub. Isso evita que a gente modifique um arquivo em dois lugares diferentes mantendo versões incompatíveis.

Por este motivo, acredito que o ideal seria traduzir em HTML. No entanto acho que seria muito bom ter os arquivos em .MD aqui no GitHub também, para quem quiser ler por aqui. 

Por uma questão de controle de versão, pensei em uma solução híbrida. A gente continua traduzindo os arquivos .html e você utiliza seu script para gerar os .md correspondentes. O que você acha? Dessa forma, teremos o .md e o .html aqui no nosso GitHub.

Terceiro ponto. Infelizmente, tive que aceitar uma tradução do rpow que foi submetida ontem, [9 horas antes](https://github.com/cypherpunksbr/cypherpunks.com.br/pull/15) de você submeter a sua. Tentamos organizar o fluxo [por aqui](https://github.com/cypherpunksbr/cypherpunks.com.br/blob/master/todo/README.md) inserindo quais artigos estão sendo traduzidos. Peço desculpas pelo seu retrabalho. Mas foi bom que serviu para eu adicionar o item dois [neste arquivo](https://github.com/cypherpunksbr/cypherpunks.com.br/blob/master/CONTRIBUTING.md). Ainda estamos organizando as coisas por aqui. É por este motivo que precisamos de pessoas como você. Temos muitas tarefas pendentes e muito trabalho.

**Comment by davimello28** [comment]
@AvelinoMorganti,

Quanto a tradução do RPOW, fiz ela em menos de 10 minutos como prova de conceito, por isso não existe nenhum problema em ignorá-la. Já estou traduzindo alguns dos artigos mais técnicos e devo fazer o pull de um deles até o horário do almoço. 

Quanto ao ponto principal, sobre os arquivos .MD, existe uma pequena função do Wordpress que [automaticamente aceita o Markdown dentro da plataforma](https://en.support.wordpress.com/markdown/). Isto é importante, pois sinaliza que possivelmente os futuros editores aceitarão o markdown como um padrão para formatação de escrita (GitHub, Ghost, Trello), e podem haver problemas de migração. 

Sou desenvolvedor, e caso necessário seja, posso me encarregar - mediante a uma boa dose de tolerância em relação ao tempo - de refazer o script para que ele leia os arquivos .MD e renderize o HTML/CSS automaticamente. Vou fazer as traduções em arquivos .MD e compilar para HTML no modelo apresentado!

**Comment by davimello28** [comment]
Estou relendo o artigo mais uma vez para verificar se não cometi nenhum erro em relação a algum termo matemático. Segue o preview.

Intrapolynomial Cryptography
Nick Szabo
=============================

#### 1999

Pesquisadores tem proposto uma variedade de "desafios para clientes" e "trabalho pesado" como o hashcash, MicroMint, Bit Gold e a Postagem com Custo Computacional para criar uma moeda independente ou fazer o spam ficar custoso. As implicações matemáticas desta proposta é de que existe uma "Criptografia Intrapolinomial". As 4 motivações para a teoria da criptografia intrapolinomial são (a) novas construções como as mencionadas anteriormente, (b) estimativas mais acuradas sobre o custo para se quebrar uma cifra, (c) é possível que seja mais fácil provar os limites menores ao invés de apenas executá-los, como nos casos da criptografia superpolinomial (padrão), e (d) se não existe nenhuma função digestiva (one-way function), a criptografia padrão é intrapolinomial ao invés de superpolinomial.

Proponho a seguinte formalização:
    

    Assumindo que: 

    f: {0,1}* --> {0,1}* é chamada de Função k-benchmark forte

    para uma máquina de um modelo M e k>=1 se:
    
    1.f for processado no tempo O(p(n)) na máquina M, onde p é polinomial.
    2.f não reduza os dados inseridos mais do que q(n,k), onde q(n,k) é um polinômio de grau k.
    3.Para cada algoritmo aleatório A que seja processado em M em um tempo menor que q(n,k)p(n), existe um N tal que n > N
        Pr[A(f(x)) = f^-1(f(x))] < 1/q(n,k)p(n)

Em outras palavras, não existe um algoritmo rodando mais rápido que q(n,k)p(n) que possa inverter f em um número significante de valores.

É possível definir casos médios, melhor dos casos e pior dos casos para a função de benchmark de grau k. O questionamento (análogo a questão da criptografia superpolinomial, se existe uma função de uma única via): pode provar (3) os limites superiores e inferiores para um função qualquer e k\>=1 em uma máquina real como a RAM-log?

Casos fortes e médios são os mais oportunos em casos relacionados a criptografia. Infelizmente, para estes propósitos nós também precisamos de:

1.  uma lista de máquinas que compreenda todos os modelos praticáveis de máquina, no sentido de que qualquer uma dessas máquinas possam ser simuladas com uma pequena sobrecarga, como uma constante ou O(log(n)).
2.  para provar os limites inferiores em uma função de benchmark para todos os modelos da lista.

Sabendo que isso é, no mínimo, muito chato, esperamos conseguir uma pequena lista que cubra todas as arquiteturas plausíveis. Isto pode funcionar para provar que a exposição total de um protocolo de quebra (cracking protocol) é menor que os custos de pesquisa e desenvolvimento de uma arquitetura para derrotar este mesmo protocolo. A análise criptográfica (cryptanalyis) deve descobrir quais arquiteturas são interessantes para quebrar uma cifra intrapolinomial.

Existe ao menos duas implicações práticas da análise anterior. A primeira é que existe pouquíssimo espaço para erro para a análise e implementação da postagem com custo computacional, hashcash, bit gold, MicroMint e outros modelos de criptografia intrapolinomiais. A segunda é que, a menos que o oponente tenha pouco dinheiro e esteja limitado a um computador pessoal, não faz sentido analisar a segurança ou o custo desses esquemas sem fazer referência a arquitetura da máquina. Por exemplo, propagadores de spam (spammers) poderiam acabar com o custo computacional usando placas artesanais otimizadas para resolver um problema particular.

**Comment by AvelinoMorganti** [comment]
Seria interessante ter seu script para converter html para .MD. Assim podemos disponibilizar no GitHub também!

@davimello28 preciso do seu usuário no Telegram para te adicionar em um grupo. Preciso de algumas informações suas para te enviar uma camiseta. Obrigado pelas suas contribuições :)

**Comment by davimello28** [comment]
@AvelinoMorganti, o Pandoc converte praticamente qualquer coisa para qualquer coisa. Eu consigo converter todos os HTMLs para MD em um clique. Posso postá-los em breve, entretanto peço a paciência dos senhores, pois minha semana tem sido dura. 

Importante destacar que estou traduzindo o artigo sobre Linguagem dos Constratos do Szabo em paralelo. É um dos maiores artigos, então talvez leve um pouco de tempo.

Estou enviando meu usuário diretamente a você. Entretanto, observei que minha meta em relação aos artigos ainda não foi batida. Isso está correto?

**Comment by AvelinoMorganti** [comment]
O site foi reformulado. Colocaremos textos em .html com opção para .md também.
