### ISSUE TITLE
The GNU/Linux Crypto Series

### ISSUE THREAD

**Issue by hanelore** [cypherpunksbr/cypherpunks.com.br#23]
Hi, can I insert the The GNU/Linux Crypto Series in the roadmap and remix with a smaller version?

Already exists a Portuguese version by [Rafael Beraldo](https://github.com/rberaldo) in his [https://github.com/rberaldo/cabaladada](blog).

**References:**

https://sanctum.geek.nz/arabesque/series/gnu-linux-crypto/

https://cabaladada.org/2013/09/16/linux_cripto_intro/

Thanks.

**Comment by davimello28** [comment]
I was expecting to see more articles about GNU/Linux here, although I believe that we should keep subjects as divided as possible to keep it organized. Cryptography is a **huge** subject, so before one starts to translate, I believe it is important to think about how to categorize those articles properly.

**Comment by davimello28** [comment]
I think we have two ways of doing so:

1. Tag posts: this way you can post any content, any time and search for those tags later on. 
2. Put up some categories as tabs on the start menu and click for the content. 

I am not sure if the blog already supports any of those methods. I am pretty sure that Wordpress itself does support it.

**Comment by AvelinoMorganti** [comment]
@hanelore I think that's a great suggestion. I added it [in this file](https://github.com/cypherpunksbr/cypherpunks.com.br/blob/master/todo/README.md) as a suggestion for all members.

Initially, our focus is to translate the [Nakamoto Institute](https://nakamotoinstitute.org/literature/) files and Satoshi's emails. But I believe this subject is pertinent to our project. Feel free to translate it too if you want.

**Comment by AvelinoMorganti** [comment]
@hanelore I need your user on Telegram to add you to group. I need some information from you to send you a free T-shirt. Thanks for your contributions :)

**Comment by hanelore** [comment]
@AvelinoMorganti and @davimello28 thanks again. I am in the Telegram [group](https://t.me/criptologia), about the t-shirt you can leave it available for another contributor, because I am under pseudonym.

This issue can be closed now, I think... Thanks again and let's work.

**Comment by AvelinoMorganti** [comment]
Thank you both for the collaborative spirit.
