### ISSUE TITLE
Fluxo para tradução de textos

### ISSUE THREAD

**Issue by dav1app** [cypherpunksbr/cypherpunks.com.br#42]
Prezados, 

Identifiquei um possível ponto de atrito que poderia ser esclarecido em nosso [guia](https://github.com/cypherpunksbr/cypherpunks.com.br/blob/master/CONTRIBUTING.md). 

Existe uma dificuldade, ao menos por minha parte, de identificar exatamente quais são os arquivos que necessitam de alteração nos processos de tradução, revisão e inserção de um texto. 

Estou criando este tópico para que tais questões sejam esclarecidas antes de subir uma nova proposta de guia para o grupo. É importante destacar que estou me referenciando aos estágios da tradução de forma abstrata, não respeitando a nomenclatura usada no momento, afim de facilitar a abstração destes estágios. 

Note que estou sendo extremamente prolixo somente para favorecer a discussão. O método em si é simples. 

As diferenças principais do modelo proposto para o modelo atual são:

- Lista única de artigos, variando de status que vão desde `TO_TRANSLATE` até `FINISHED`, passando por todas as etapas de revisão. Na lista, os artigos deverão ser compostos por TÍTULO, AUTOR e ANO do artigo. 
- O status de `FINISHED` é criado quando um artigo é proposto, traduzido e revisado 20 vezes, conforme descrito [aqui](cypherpunks.com.br/posts/README.md)
- Pastas serão organizadas através do estágio de cada artigo, não sendo criadas pastas de acordo com o formato. Qualquer arquivo inserido em pastas diferentes da TO_TRANSLATE deverá seguir o formato padrão (que está sendo discutido no presente momento no grupo do Telegram e [aqui](https://github.com/cypherpunksbr/cypherpunks.com.br/issues/16)).
- Seria interessante existir uma formalização em relação ao nome das branchs, não proposto por esta alteração.

### Fluxo para tradução de textos

1. Criar o fork do repositório e adicionar este aos upstreams.
2. Selecionar o artigo que desejar traduzir, este deverá estar presente na lista de artigos que ainda estão em TO TRANSLATE. 
3. Criar uma nova branch com um nome associado ao artigo que se está traduzindo, preferencialmente iniciado por `traducao`, seguido do nome genérico do artigo.
3. Realizar um pull request deste arquivo de tradução, movendo-o de TO TRANSLATE para TRANSLATING.
4. Aguardar até que a pull request seja aceita para iniciar a tradução.
5. Realizar a tradução do artigo.
6. Realizar um pull request do artigo traduzido, modificando o status de TRANSLATING para TRANSLATED.

### Fluxo para revisão de textos

1. Criar o fork do repositório e adicionar este aos upstreams.
2. Selecionar os artigos que se deseja criar a revisão. 
3. Criar uma branch iniciada por `revisao`
3. Realizar a mudança de uma lista, ainda inexistente, de TO REVISE, para REVISING.
4. Diferentemente da tradução, este commit poderá ocorrer dentro do mesmo pull que a revisão, sem a necessidade de se aguardar a aprovação. A tese é de que revisões vão alterar uma parte pequena do texto, e caso ocorra um conflito, a última pessoa poderá ser responsável por realizar um merge e alterar a quantidade de revisões do mesmo texto.
5. Realizar um pull request da ultima versão do texto, modificando seu status de REVISING para REVISED[%%], onde %% é o número de revisões que aquele texto recebeu. Um texto deverá conter ao mínimo 5 revisões para que seja considerado válido, e poderá conter até 20 revisões, conforme o descrito [aqui]( cypherpunks.com.br/posts/README.md). 
6. Após o limite de 20 revisões, o texto receberá o status de FINAL. 

### Fluxo para submeter novos textos para a tradução.

1. Criar o fork do repositório e adicionar este aos upstreams.
2. Verificar se já não há um texto com o mesmo título e autor na lista, independente do seu status.
3. Criar uma proposta de inserção de texto através de uma Issue para validar se existe consenso em incluir o texto na lista de artigos. 
4. Caso o texto tenha resposta positiva, o propositor deverá criar uma pull request contendo o título do texto a ser traduzido, o autor, o ano (tendo em vista que ocorrem revisões das versões finais destes artigos) com o status de TO DO. 
5. Caso já exista algum arquivo base para a tradução, seja um PDF, HTML, TXT, MD ou qualquer outro formato que possa ser consumido para equipe tradutora, este arquivo deverá ser postado na pasta de arquivos TO DO (que está diferente do modelo atual), sendo feito dentro do mesmo pull request. Para arquivos que precisem de mais de uma unidade (ex: PDFs divididos, imagens), o artigo deverá ser inserido usando-se uma pasta.

**Comment by matheusbach** [comment]
Novo fluxo para tradução de textos para pt-br

https://cypherpunks.com.br/documentos/contribuir-cypherpunksbr/#traduzindo-documentos-para-portugu%c3%aas-pt-br
