### ISSUE TITLE
Inclusão de eBooks

### ISSUE THREAD

**Issue by ghost** [cypherpunksbr/cypherpunks.com.br#57]
Vejo que a pasta _pdfs_ conta com apenas um arquivo. O objetivo é incluir apenas artigos e/ou textos traduzidos/revisados pelos colaboradores? Ou pretendem montar uma ampla biblioteca? Possuo alguns ebooks sobre programação, escola austríaca, bitcoin e afins. Poderia incluí-los?

**Comment by AvelinoMorganti** [comment]
Em /pdf/ pretendemos adicionar livros, material suplementar e os artigos traduzidos no formato .pdf

Se você achar algum material pertinente, pode incluir sim :)
