### ISSUE TITLE
Por onde iniciar as contribuições?

### ISSUE THREAD

**Issue by yuricwe** [cypherpunksbr/cypherpunks.com.br#84]
Olá pessoal, estou a fim de contribuir com a page com algumas traduções ou revisões para testar o que aprendi de Git e GitHub contribuindo em um projeto real e que eu vejo sentido

**Algumas duvidas (já li o CONTRIBUTING.md e tudo o mais)**

1) Tem alguma ordem na tradução dos textos ou existe algum mais urgente?

2) Vi na lista de revisões que mesmo textos sem as 5 revisões estão indo pro site.Não seria o caso de atualizar aquele readme.md do /site/html?

3) Onde está publicado o conteúdo do /pages ? No site eu só achei o que está no /site. Seria o /pages uma versão anterior do /site?

**Comment by yuricwe** [comment]
Pensei em começar a contribuir traduzindo o [smart contract glossary](https://github.com/cypherpunksbr/cypherpunks.com.br/blob/master/todo/smart-contracts-glossary.html) do Nick Szabo.

É um documento simples de se traduzir e seria uma contribuição boa para a comunidade cripto Br ao meu ver.

**Comment by iramaro** [comment]
Olá @yuricwe desculpe a demora em responde-lo. A dinâmica da página (inclusive o layout) mudaram de uns tempos para cá. Os artigos já traduzidos estão em https://cypherpunks.com.br/html/ algumas coisas estão fora do padrão em relação ao rito proposto. Mas sinta-se livre para traduzir um artigo que já não esteja na URL citada acima ou revisar um já existente e mandar um PR.

**Comment by yuricwe** [comment]
Obrigado pela resposta @iramaro 

Terminei a tradução do artigo do Nick Szabo que havia mencionado e já fiz o PR. Sou iniciante no GitHub, mas acho que fiz tudo certo. Qualquer coisa é só me falar. Espero que ajude.

**Comment by viniciusyaunner** [comment]
Boa noite @yuricwe, fizemos mudança no site, agora as traduções vão para a pasta **/post** seguindo o formato dos textos atuais, agora é possivel fazer a tradução usando markdown

Em breve farei um novo guia para o novo fluxo de traduções.

**Comment by matheusbach** [comment]
Novo guia

https://cypherpunks.com.br/documentos/contribuir-cypherpunksbr/
